<a href="https://colab.research.google.com/github/gigiosbarbr/potifolio-giovane/blob/main/Day_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import pandas as pd
import matplotlib.pyplot as plt


In [39]:
df_ordem_items = pd.read_csv('/content/drive/MyDrive/Bases Day 9/DNC_order_items_dataset.csv')
df_ordem_reviews = pd.read_csv('/content/drive/MyDrive/Bases Day 9/DNC_order_reviews_dataset.csv')
df_products = pd.read_csv('/content/drive/MyDrive/Bases Day 9/DNC_products_dataset.csv')
df_orders = pd.read_csv('/content/drive/MyDrive/Bases Day 9/DNC_orders_dataset.csv')


In [40]:
df_ordem_items.head()

Unnamed: 0                          order_id  order_item_id  \
0           0  00010242fe8c5a6d1ba2dd792cb16214              1   
1           1  00018f77f2f0320c557190d7a144bdd3              1   
2           2  000229ec398224ef6ca0657da4fc703e              1   
3           3  00024acbcdf0a6daa1e931b038114c75              1   
4           4  00042b26cf59d7ce69dfabb4e55b4fd9              1   

                         product_id   price  
0  4244733e06e7ecb4970a6e2683c13e61   58.90  
1  e5f2d52b802189ee658865ca93d83a8f  239.90  
2  c777355d18b72b67abbeef9df44fd0fd  199.00  
3  7634da152a4610f1595efa32f14722fc   12.99  
4  ac6c3623068f30de03045865e4e10089  199.90

In [41]:
df_ordem_reviews.head()

Unnamed: 0                         review_id  \
0           0  7bc2406110b926393aa56f80a40eba40   
1           1  80e641a11e56f04c1ad469d5645fdfde   
2           2  228ce5500dc1d8e020d8d1322874b6f0   
3           3  e64fb393e7b32834bb789ff8bb30750e   
4           4  f7c4243c7fe1938f181bec41a392bdeb   

                           order_id  review_score  
0  73fc7af87114b39712e6da79b0a377eb             4  
1  a548910a1c6147796b98fdf73dbeba33             5  
2  f9e4b658b201a9f2ecdecbb34bed034b             5  
3  658677c97b385a9be170737859d3511b             5  
4  8e6bfb81e283fa7e4f11123a3fb894f1             5

In [42]:
df_products.head()

Unnamed: 0                        product_id  product_category_name  \
0           0  1e9e8ef04dbcff4541ed26657ea517e5             perfumaria   
1           1  3aa071139cb16b67ca9e5dea641aaa2f                  artes   
2           2  96bd76ec8810374ed1b65e291975717f          esporte_lazer   
3           3  cef67bcfe19066a932b7673e239eb23d                  bebes   
4           4  9dc1a7de274444849c219cff195d0b71  utilidades_domesticas   

   product_name_lenght  product_description_lenght  product_weight_g  \
0                 40.0                       287.0             225.0   
1                 44.0                       276.0            1000.0   
2                 46.0                       250.0             154.0   
3                 27.0                       261.0             371.0   
4                 37.0                       402.0             625.0   

   product_length_cm  product_height_cm  product_width_cm  
0               16.0               10.0              14.0  
1               30.0               18.0              20.0  
2               18.0                9.0              15.0  
3               26.0                4.0              26.0  
4               20.0               17.0              13.0

In [43]:
df_orders.head()

Unnamed: 0                          order_id  \
0           0  e481f51cbdc54678b7cc49136f2d6af7   
1           1  53cdb2fc8bc7dce0b6741e2150273451   
2           2  47770eb9100c2d0c44946d9cf07ec65d   
3           3  949d5b44dbf5de918fe9c16f97b45f8a   
4           4  ad21c59c0840e6cb83a9ceb5573f8159   

                        customer_id order_status  
0  9ef432eb6251297304e76186b10a928d    delivered  
1  b0830fb4747a6c6d20dea0b8c802d7ef    delivered  
2  41ce2a54c0b03bf3443c3d931a367089    delivered  
3  f88197465ea7920adcdbec7375364d82    delivered  
4  8ab97904e6daea8866dbdbc4fb7aad2c    delivered

In [44]:
df_cliente_prod =pd.merge(df_ordem_reviews,df_orders, on = 'order_id')

In [45]:
df_cliente_prod.head()

Unnamed: 0_x                         review_id  \
0             0  7bc2406110b926393aa56f80a40eba40   
1             1  80e641a11e56f04c1ad469d5645fdfde   
2             2  228ce5500dc1d8e020d8d1322874b6f0   
3             3  e64fb393e7b32834bb789ff8bb30750e   
4             4  f7c4243c7fe1938f181bec41a392bdeb   

                           order_id  review_score  Unnamed: 0_y  \
0  73fc7af87114b39712e6da79b0a377eb             4          1871   
1  a548910a1c6147796b98fdf73dbeba33             5         90488   
2  f9e4b658b201a9f2ecdecbb34bed034b             5         78882   
3  658677c97b385a9be170737859d3511b             5         27557   
4  8e6bfb81e283fa7e4f11123a3fb894f1             5         79505   

                        customer_id order_status  
0  41dcb106f807e993532d446263290104    delivered  
1  8a2e7ef9053dea531e4dc76bd6d853e6    delivered  
2  e226dfed6544df5b7b87a48208690feb    delivered  
3  de6dff97e5f1ba84a3cd9a3bc97df5f6    delivered  
4  5986b333ca0d44534a156a52a8e33a83    delivered

In [46]:
df_cliente_prod = pd.merge(df_cliente_prod, df_ordem_items, on = 'order_id')

In [47]:
df_cliente_prod.head()

Unnamed: 0_x                         review_id  \
0             0  7bc2406110b926393aa56f80a40eba40   
1             0  7bc2406110b926393aa56f80a40eba40   
2             1  80e641a11e56f04c1ad469d5645fdfde   
3             2  228ce5500dc1d8e020d8d1322874b6f0   
4             3  e64fb393e7b32834bb789ff8bb30750e   

                           order_id  review_score  Unnamed: 0_y  \
0  73fc7af87114b39712e6da79b0a377eb             4          1871   
1  73fc7af87114b39712e6da79b0a377eb             4          1871   
2  a548910a1c6147796b98fdf73dbeba33             5         90488   
3  f9e4b658b201a9f2ecdecbb34bed034b             5         78882   
4  658677c97b385a9be170737859d3511b             5         27557   

                        customer_id order_status  Unnamed: 0  order_item_id  \
0  41dcb106f807e993532d446263290104    delivered       51033              1   
1  41dcb106f807e993532d446263290104    delivered       51034              2   
2  8a2e7ef9053dea531e4dc76bd6d853e6    delivered       72472              1   
3  e226dfed6544df5b7b87a48208690feb    delivered      109962              1   
4  de6dff97e5f1ba84a3cd9a3bc97df5f6    delivered       44664              1   

                         product_id   price  
0  fd25ab760bfbba13c198fa3b4f1a0cd3  185.00  
1  fd25ab760bfbba13c198fa3b4f1a0cd3  185.00  
2  be0dbdc3d67d55727a65d4cd696ca73c   79.79  
3  d1c427060a0f73f6b889a5c7c61f2ac4  149.00  
4  52c80cedd4e90108bf4fa6a206ef6b03  179.99

In [48]:
df_cliente_prod_score = df_cliente_prod[['customer_id', 'product_id', 'review_score']]

In [59]:
df_cliente_prod_score.head()

customer_id                        product_id  \
0  41dcb106f807e993532d446263290104  fd25ab760bfbba13c198fa3b4f1a0cd3   
1  41dcb106f807e993532d446263290104  fd25ab760bfbba13c198fa3b4f1a0cd3   
2  8a2e7ef9053dea531e4dc76bd6d853e6  be0dbdc3d67d55727a65d4cd696ca73c   
3  e226dfed6544df5b7b87a48208690feb  d1c427060a0f73f6b889a5c7c61f2ac4   
4  de6dff97e5f1ba84a3cd9a3bc97df5f6  52c80cedd4e90108bf4fa6a206ef6b03   

   review_score  
0             4  
1             4  
2             5  
3             5  
4             5

In [49]:
len(df_cliente_prod_score['product_id'].unique())

32789

In [50]:
import numpy as np


def start_pipeline(dataf):
    return dataf.copy()

def get_book_counts(dataf):
  return dataf.groupby(by='product_id', as_index=False) \
    .agg({'customer_id': pd.Series.nunique}) \
    .rename(columns={'customer_id': 'customer_id_count'}) \
    .set_index('product_id') \
    .sort_values('customer_id_count', ascending = False)

def get_avg_ratings(dataf):
  return dataf.groupby(by='product_id', as_index=False) \
    .agg({'review_score' : np.mean}) \
    .rename(columns={'review_score': 'review_score_avg'}) \
    .set_index('product_id') \
    .sort_values('review_score_avg', ascending = False)

def get_n_top_values(dataf, n):
  return dataf.head(n) \
    .index \
    .tolist()

top_produtos_ratings = df_cliente_prod_score \
  .pipe(start_pipeline) \
  .pipe(get_avg_ratings) \
  .pipe(get_n_top_values, n=3000)

top_produtos_sellers = df_cliente_prod_score \
  .pipe(start_pipeline) \
  .pipe(get_book_counts) \
  .pipe(get_n_top_values, n=10)

top_produtos_ratings[:10], top_produtos_sellers

(['00066f42aeeb9f3007548bb9d3f33c38',
  '60314cbf527af04ebc935be7c02dc1cd',
  '5fe23e6307c231e287f13c0a4be06c88',
  '5fe490e61e7a37f2f0d1ad1771ac027d',
  'c696cd2db7870be08c37822f7c0ef831',
  '5fef486f2057e10fd91e167348812b7a',
  '5ff4076c0f01eeba4f728c9e3fa2653c',
  '5ff59c5f2db7600fa8143442c8b1e4f6',
  'c68b419d9c6038271b85bac98adb0fc9',
  '5ffa5bcfb017e836862c86ec3fbf9045'],
 ['99a4788cb24856965c36a24e339b6058',
  'aca2eb7d00ea1a7b8ebd4e68314663af',
  '422879e10f46682990de24d770e7f83d',
  'd1c427060a0f73f6b889a5c7c61f2ac4',
  '389d119b48cf3043d311335e499d9c6b',
  '53b36df67ebb7c41585e8d54d6772e08',
  '368c6c730842d78016ad823897a372db',
  '53759a2ecddad2bb87a079a1f1519f73',
  '154e7e31ebfa092203795c972e5804a6',
  '2b4609f8948be18874494203496bc318'])

In [51]:
df_cliente_prod_score.head()

customer_id                        product_id  \
0  41dcb106f807e993532d446263290104  fd25ab760bfbba13c198fa3b4f1a0cd3   
1  41dcb106f807e993532d446263290104  fd25ab760bfbba13c198fa3b4f1a0cd3   
2  8a2e7ef9053dea531e4dc76bd6d853e6  be0dbdc3d67d55727a65d4cd696ca73c   
3  e226dfed6544df5b7b87a48208690feb  d1c427060a0f73f6b889a5c7c61f2ac4   
4  de6dff97e5f1ba84a3cd9a3bc97df5f6  52c80cedd4e90108bf4fa6a206ef6b03   

   review_score  
0             4  
1             4  
2             5  
3             5  
4             5

In [52]:
matriz_de_relacionamento_top_produtos_ratings = df_cliente_prod_score[df_cliente_prod_score["product_id"].isin(top_produtos_ratings)] \
  .pivot_table(index="product_id", columns="customer_id", values="review_score").fillna(0)

matriz_de_relacionamento_top_produtos_ratings.shape

(3000, 3820)

In [57]:
matriz_de_relacionamento_top_produtos_ratings.head()

customer_id                       000598caf2ef4117407665ac33275130  \
product_id                                                           
00066f42aeeb9f3007548bb9d3f33c38                               0.0   
4013f49ee9fda2d3eb99e7923cba7982                               0.0   
40161099308e1f5f784d57e2b88b31b5                               0.0   
401b500ac0cf49fd24047ba60015a7ae                               0.0   
402e8d6a95c83da5c3cef16b795329b9                               0.0   

customer_id                       00205ad9ba1ef4340cef86583294cf82  \
product_id                                                           
00066f42aeeb9f3007548bb9d3f33c38                               0.0   
4013f49ee9fda2d3eb99e7923cba7982                               0.0   
40161099308e1f5f784d57e2b88b31b5                               0.0   
401b500ac0cf49fd24047ba60015a7ae                               0.0   
402e8d6a95c83da5c3cef16b795329b9                               0.0   

customer_id                       002236c4f333bc8df6a5939749eb7869  \
product_id                                                           
00066f42aeeb9f3007548bb9d3f33c38                               0.0   
4013f49ee9fda2d3eb99e7923cba7982                               0.0   
40161099308e1f5f784d57e2b88b31b5                               0.0   
401b500ac0cf49fd24047ba60015a7ae                               0.0   
402e8d6a95c83da5c3cef16b795329b9                               0.0   

customer_id                       002834b4d901534f48d9e9a72047b288  \
product_id                                                           
00066f42aeeb9f3007548bb9d3f33c38                               0.0   
4013f49ee9fda2d3eb99e7923cba7982                               0.0   
40161099308e1f5f784d57e2b88b31b5                               0.0   
401b500ac0cf49fd24047ba60015a7ae                               0.0   
402e8d6a95c83da5c3cef16b795329b9                               0.0   

customer_id                       002c625393dfa194828b462a6ef8cb0b  \
product_id                                                           
00066f42aeeb9f3007548bb9d3f33c38                               0.0   
4013f49ee9fda2d3eb99e7923cba7982                               0.0   
40161099308e1f5f784d57e2b88b31b5                               0.0   
401b500ac0cf49fd24047ba60015a7ae                               0.0   
402e8d6a95c83da5c3cef16b795329b9                               0.0   

customer_id                       0036875772a8eeb391b8cd7226283fdd  \
product_id                                                           
00066f42aeeb9f3007548bb9d3f33c38                               0.0   
4013f49ee9fda2d3eb99e7923cba7982                               0.0   
40161099308e1f5f784d57e2b88b31b5                               0.0   
401b500ac0cf49fd24047ba60015a7ae                               0.0   
402e8d6a95c83da5c3cef16b795329b9                               0.0   

customer_id                       003ec17a1389fa302f3a0423dddd8650  \
product_id                                                           
00066f42aeeb9f3007548bb9d3f33c38                               0.0   
4013f49ee9fda2d3eb99e7923cba7982                               0.0   
40161099308e1f5f784d57e2b88b31b5                               0.0   
401b500ac0cf49fd24047ba60015a7ae                               0.0   
402e8d6a95c83da5c3cef16b795329b9                               0.0   

customer_id                       0043b0afd67fb3af74360d2893b9a530  \
product_id                                                           
00066f42aeeb9f3007548bb9d3f33c38                               0.0   
4013f49ee9fda2d3eb99e7923cba7982                               0.0   
40161099308e1f5f784d57e2b88b31b5                               0.0   
401b500ac0cf49fd24047ba60015a7ae                               0.0   
402e8d6a95c83da5c3cef16b795329b9                               0.0   

customer_id                       006d300ffcb82917c9866dd5a507dbe6  \
pr

In [53]:
from sklearn.metrics.pairwise import cosine_similarity


cos_prod = cosine_similarity(matriz_de_relacionamento_top_produtos_ratings)

print(cos_prod)
cos_prod.shape

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


(3000, 3000)

In [54]:
def recomendar(id_prod):
  print(f"Produto de interesse: {id_prod}")
  try:
    prod_idx = matriz_de_relacionamento_top_produtos_ratings.index.tolist().index(id_prod)
    closest_10_prod = np.argsort(-cos_prod[prod_idx])[1:11]
    print(f"Retornando 10 produtos mais próximos de: {id_prod}.")
    return matriz_de_relacionamento_top_produtos_ratings.index[closest_10_prod].tolist()
  except ValueError as e:
    print(f"{id_prod}, não está incluso na matriz de recomendação. Retornando os 10 mais avaliados")
    return top_produtos_sellers

In [64]:
id_prod_interesse = "00066f42aeeb9f3007548bb9d3f33c38"
ids_10_mais_proximos = recomendar(id_prod_interesse)

ids_10_mais_proximos

Produto de interesse: 00066f42aeeb9f3007548bb9d3f33c38
Retornando 10 produtos mais próximos de: 00066f42aeeb9f3007548bb9d3f33c38.


['bf3a3366c9e0b1f5e8de3447d79c19dd',
 'bf3feeeefed5b3e4b5fed721408deac2',
 'bf477d995ee4444807afc574cfbcc1c1',
 'bf5f81431577de43f0cb0864d45f835f',
 'bf6c6addcc27daf7976e4eeeda499619',
 'bf6d369fda3cc67f960c9290d3e91158',
 'bf7504ae9c74df62ecc385f05300fe09',
 'bf7bb0eab82e5726d4401a152eb91a4a',
 'bf7caf1a1caf9c42b0aac2e68e019945',
 'bf7e9480325415ebfee169ceee8b53e0']